fixed bug with sorting after apps are closed very fast after opening …
KeikaiLauncher/KeikaiLauncher pull request #16
Opened 2020-03-21 09:57 UTC by felixbaral

When a user quits an APP very fast after opened with the Launcher the sorting got messed up. Now it is fixed

2020-03-21 14:55 UTC, avuton commented
Oh wow. Does this fix the problem where the launcher will only show a subset of apps sometimes? If so, this fix is gold. Give me a few days to find time, reacquaint myself with the code and I'll probably pull this in. If this fixes it, it's probably fixed by the synchronization block in sortApps, which makes me wonder why I didn't use that in the first place.

2020-03-22 05:23 UTC, avuton commented on app/src/main/java/com/anpmech/launcher/activities/SearchActivity.java
Line 294 should be removed with this commit.

2020-03-22 05:25 UTC, avuton requested changes
Remove line 294 in a squashed commit and we'll be in.

2020-03-23 20:36 UTC, felixbaral commented
I hope I did that correctly. Squashed it localy and had to force push then of course. Thanks for pointing that one out. Sadly it does not fix the bug that only shows a subset of the apps. I also have that, but is is very rare.

2020-03-23 20:36 UTC, felixbaral commented
It only fixes the bug that apps are ordered wrong when you exit to the launcher very fast after an app was opened.

2020-03-23 23:50 UTC, merged

2020-03-23 23:56 UTC, avuton commented
Thanks for the fix. I don't think I ever witnessed this one, but it looks correct, regardless.